### ISSUE TITLE
Why every single issue here starts with "Why[...]"?

### ISSUE THREAD

**Issue by kress95** [DestructHub/unnatural-apda#8]
Why?

**Comment by ryukinix** [comment]
Because why is always the best way to force people to talk if they can.

**Comment by PedroHLC** [comment]
Because if we used answers instead of questions, we would have to start an infinite search for the question for each given answers. And we're still searching for the one which can be answered with "42".

**Comment by PedroHLC** [comment]
This issue became a lie with #9, I must close it now.

**Comment by ryukinix** [comment]
@PedroHLC thanks.

**Comment by rafaelcn** [comment]
WHY SO MANY ISSUES :sob:

**Comment by ryukinix** [comment]
@rafaelcn cry for all night, man. This is about information and discussing. We need a lot of issues to handle correctly the ideas. Mix-up is very bad.

**Comment by rafaelcn** [comment]
Fine.

**Comment by PedroHLC** [comment]
@rafaelcn We're replying them all with a telegram bot, so the more the better :P

**Comment by ryukinix** [comment]
:laughing:

**Comment by rafaelcn** [comment]
@ryukinix UOW

**Comment by luizperes** [comment]
lol

**Comment by kress95** [comment]
lol

**Comment by ryukinix** [comment]
@kress95 lol

**Comment by ryukinix** [comment]
@ryukinix
